server:
    port: 8000

spring:
    config:
        import: classpath:application-test.yml, application-dev.yml
    profiles:
        include:
            - test
        group:
            dev: dev

    jpa:
        show-sql: true